FROM python:3.9-slim

WORKDIR /app

COPY fulfillment.py requirements.txt ./
RUN pip install -r requirements.txt

ENV GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

EXPOSE 5000

CMD ["python", "fulfillment.py"]